// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW71ttFo_XxjWSslGRmp5M9qt2vbhCE3s',
    appId: '1:1004494078901:web:60bf13f47e95ef50328ffc',
    messagingSenderId: '1004494078901',
    projectId: 'intelligent-plant',
    authDomain: 'intelligent-plant.firebaseapp.com',
    databaseURL: 'https://intelligent-plant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligent-plant.appspot.com',
    measurementId: 'G-H0CTKZEX8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzmauK_9zydupO6YNik2ImHg1dRqzZYYc',
    appId: '1:1004494078901:android:8554d36d53720a8b328ffc',
    messagingSenderId: '1004494078901',
    projectId: 'intelligent-plant',
    databaseURL: 'https://intelligent-plant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligent-plant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALifMcvwTKooIE3NFHgwWnuwsjotRR_Uo',
    appId: '1:1004494078901:ios:926d5055b1c4dc56328ffc',
    messagingSenderId: '1004494078901',
    projectId: 'intelligent-plant',
    databaseURL: 'https://intelligent-plant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligent-plant.appspot.com',
    iosClientId: '1004494078901-noruuoe2ok4ud4ounkb816n8t69hnper.apps.googleusercontent.com',
    iosBundleId: 'de.dtghgthf.intelligentPlantEsp32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALifMcvwTKooIE3NFHgwWnuwsjotRR_Uo',
    appId: '1:1004494078901:ios:926d5055b1c4dc56328ffc',
    messagingSenderId: '1004494078901',
    projectId: 'intelligent-plant',
    databaseURL: 'https://intelligent-plant-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'intelligent-plant.appspot.com',
    iosClientId: '1004494078901-noruuoe2ok4ud4ounkb816n8t69hnper.apps.googleusercontent.com',
    iosBundleId: 'de.dtghgthf.intelligentPlantEsp32',
  );
}
